# Reset
ANSI_COLOR_OFF='\e[0m'       # Text Reset

# Regular Colors
ANSI_COLOR_BLACK='\e[0;30m'        # Black
ANSI_COLOR_RED='\e[0;31m'          # Red
ANSI_COLOR_GREEN='\e[0;32m'        # Green
ANSI_COLOR_YELLOW='\e[0;33m'       # Yellow
ANSI_COLOR_BLUE='\e[0;34m'         # Blue
ANSI_COLOR_PURPLE='\e[0;35m'       # Purple
ANSI_COLOR_CYAN='\e[0;36m'         # Cyan
ANSI_COLOR_WHITE='\e[0;37m'        # White

# Defined Standards
ANSI_TERMINAL_PRODUCTION=$ANSI_COLOR_RED
ANSI_TERMINAL_USER=$ANSI_COLOR_BLUE
ANSI_TERMINAL_STAGING=$ANSI_COLOR_YELLOW
ANSI_TERMINAL_DEVELOPMENT=$ANSI_COLOR_GREEN
ANSI_TERMINAL_DISPOSABLE=$ANSI_COLOR_CYAN
ANSI_TERMINAL_DEFAULT=$ANSI_COLOR_WHITE

ANSI_TERMINAL_ERROR=$ANSI_COLOR_RED
ANSI_TERMINAL_OK=$ANSI_TERMINAL_DEFAULT
ANSI_TERMINAL_SUCCESS=$ANSI_COLOR_GREEN
ANSI_TERMINAL_WARNING=$ANSI_COLOR_YELLOW
